pipeline {
    agent any
    tools {
        maven 'maven-3.5' 
    }
    stages {
        stage('Checkout') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/ilissan/armis-calc.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') { 
            steps {
                sh 'mvn test' 
            }
            post {
                always {
                    junit 'target/surefire-reports/TEST-*.xml' 
                }
            }
        }
        stage('Archive artifacts') {
            archive 'target/*.jar'
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deploy.sh' 
            }
        }
    }
}