node {
    def mvnHome
    stage('Checkout') { // for display purposes
        // Get some code from a GitHub repository
        git 'https://github.com/ilissan/armis-calc.git'
        // Get the Maven tool.         
        mvnHome = tool 'maven-3.5'
        // Get version from pom
        //def version = pom.version.replace("-SNAPSHOT", ".${currentBuild.number}")
    }
    stage('Build') {
        steps {
            sh 'mvn -B -DskipTests clean package'
        }
    }
    stage('Test') { 
        steps {
            sh 'mvn test' 
        }
        post {
            always {
                junit 'target/surefire-reports/TEST-*.xml' 
            }
        }
    }
    stage('Archive artifacts') {
        archive 'target/*.jar'
    }
    stage('Deliver') { 
        steps {
            sh './jenkins/scripts/deploy.sh' 
        }
    }
}